config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'businesses#index', as: :authenticated_root
  end
  unauthenticated :user do
    root to: 'pages#home'
  end
  devise_for :users,
  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :businesses do
    resources :items, only: :index, to: "businesses#items"
    resources :contacts do
      member do
        get '/invoices', to: "contacts#invoices", defaults: { format: 'pdf' }
      end
    end

    resources :expenses do
      member do
        get '/print', to: "expenses#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :expenses do
      member do
        get '/print', to: "expenses#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :invoices do
      member do
        get '/print', to: "invoices#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :payments do
      member do
        get '/print', to: "payments#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :invoice_equivalents do
      member do
        get '/print', to: "invoice_equivalents#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :attachments, only: :show
    resources :exports, only: [:new, :create]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  before_validation :add_invoice_number, on: :create

  belongs_to :business
  belongs_to :contact
  has_many :items, dependent: :nullify, inverse_of: :invoice
  has_many :payments, dependent: :destroy

  accepts_nested_attributes_for :items, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }
  validates :date, :expiration_date, presence: true
  mount_uploader :signature, LogoUploader
  monetize :amount_paid_cents
  monetize :amount_retained_cents

  def formated_number
    format("%03d", number)
  end

  def pdf_file_name
    "#{formated_number} FV #{contact.name} #{date}"
  end

  def name
    "Factura de Venta #{formated_number}"
  end

  def status
    if debt.zero?
      "Cobrada"
    else
      "Por Cobrar"
    end
  end

  def formated_date
    date.strftime("%d/%m/%Y")
  end

  def formated_expiration_date
    expiration_date.strftime("%d/%m/%Y")
  end

  def items_gross_subtotal
    sum = 0
    items.each do |item|
      sum += item.gross_total
    end
    return sum
  end

  def items_discount_subtotal
    sum = 0
    items.each do |item|
      sum -= item.discount_amount
    end
    return sum
  end

  def items_vat_subtotal
    sum = 0
    items.each do |item|
      sum += item.vat_amount
    end
    return sum
  end

  def items_net_subtotal
    items_gross_subtotal + items_discount_subtotal
  end

  def total
    items_net_subtotal + items_vat_subtotal
  end

  def amount_paid_cents
    payments.sum(:amount_cents)
  end

  def amount_retained_cents
    payments.sum(:retention_cents)
  end

  def debt
    total - amount_paid - amount_retained
  end

  def resolution_number?(business)
    resolution_number || business.invoice_resolution_number
  end

  def terms_and_conditions?(business)
    terms_and_conditions || business.invoice_terms_and_conditions
  end

  def notes?(business)
    notes || business.invoice_notes
  end

  def term
    (date..expiration_date).count
  end

  def signature?
    return unless signature.file || business.signature.file

    signature.file ? signature : business.signature
  end

  private

  def add_invoice_number
    self.number = business.invoices.size + 1
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_business, except: :update
  before_action :set_invoice, only: %i[show edit update destroy print toggle_printed]

  def index
    @invoices = policy_scope(Invoice.where(business: @business).order(number: :desc).includes(:contact).paginate(page: params[:page]))
  end

  def show
    @items = @invoice.items
    authorize @invoice
  end

  def new
    @invoice = Invoice.new
    @item = Item.new
    authorize @business, :business_of_current_user?
  end

  def create
    @invoice = Invoice.new(invoice_params)
    authorize @business, :business_of_current_user?
    if @invoice.save
      flash[:notice] = "Factura guardada existosamente"
      redirect_to business_invoices_path @business
    else
      @item = Item.new
      render :new
    end
  end

  def edit
    authorize @invoice
  end

  def update
    @business = Business.find(invoice_params[:business_id])
    authorize @business, :business_of_current_user?
    if @invoice.update(invoice_params)
      respond_to do |format|
        format.html do
          flash[:notice] = "Factura actualizada existosamente"
          redirect_to business_invoices_path @business
        end
        format.js
      end
    else
      @item = Item.new
      render :new
    end
  end

  def destroy
    authorize @invoice
    @invoice.destroy
    flash[:notice] = "Factura eliminada existosamente"
    redirect_to business_invoices_path(@business)
  end

  def print
    authorize @invoice
    @contact = @invoice.contact
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: @invoice.pdf_file_name, layout: 'pdf.html', show_as_html: params.key?('debug')   # Excluding ".pdf" extension.
      end
    end
  end

  def toggle_printed
    @invoice.update(printed: !@invoice.printed)
  end

  private

  def set_invoice
    @invoice = Invoice.includes(:contact).find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(
      :number,
      :contact_id,
      :date,
      :expiration_date,
      :signature,
      :terms_and_conditions,
      :notes,
      :resolution_number,
      :business_id,
      items_attributes: [:id,
                         :name,
                         :quantity,
                         :price,
                         :vat,
                         :discount,
                         "_destroy",
                         "id"]
    )
  end
end

app/views/invoices/edit.html.erb
<%= render "shared/sidebar" %>
<div class="page-content-wrapper">
  <div class="invoice-form-container">
    <div class="new-invoice-form-container">
      <%= render 'shared/invoice-form' %>
    </div>
  </div>
</div>

app/views/invoices/index.html.erb
<%= render 'shared/sidebar' %>
<div class="page-content-wrapper">
  <% if @invoices.size == 0 %>
    <h3 class="alert alert-blue property-title text-center">
      <i class="material-icons">
       info
      </i>
      Aún no tienes ningúna factura, agrega una para comenzar
    </h3>
  <% else %>
    <h1 class="app-index-title">Lista de Facturas</h1>
    <div class="table-container table-container--no-margin-bottom">
      <div class="table">
        <div class="table-row">
          <div class="table-header">Número</div>
          <div class="table-header">Cliente</div>
          <div class="table-header">Creación</div>
          <div class="table-header">Vencimiento</div>
          <div class="table-header">Total</div>
          <div class="table-header">Pagado</div>
          <div class="table-header">Por Pagar</div>
          <div class="table-header">Estado</div>
          <div class="table-header">Acciones</div>
          <div class="table-header">Impreso</div>
        </div>
        <% @invoices.each do |invoice| %>
            <div class="table-row-link table-row"
                 data-controller="table-row"
                 data-table-row-location="<%= business_invoice_path(@business, invoice)%>"
            >
              <div class="table-data" data-action="click->table-row#visitLocation"><%= invoice.formated_number %></div>
              <div class="table-data" data-action="click->table-row#visitLocation"><%= invoice.contact.name %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= invoice.date %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= invoice.expiration_date %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= humanized_money_with_symbol invoice.total %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= humanized_money_with_symbol invoice.amount_paid %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= humanized_money_with_symbol invoice.debt %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= invoice.status %></div>
              <div class="table-data white-space-no-wrap">
                <%= link_to print_business_invoice_path(@business, invoice), target: :blank  do %>
                  <i class="material-icons"> print </i>
                <% end %>
                <%= link_to edit_business_invoice_path(@business, invoice), class: "edit-property" do %>
                  <i class="material-icons"> create </i>
                <% end %>
                <%= link_to business_invoice_path(@business, invoice), class: "destroy-property", method: :delete, data: { confirm: '¿Estás seguro?' } do %>
                  <i class="material-icons"> delete </i>
                <% end %>
              </div>
              <div class="table-data">
                <%= check_box_tag 'printed', invoice.id, invoice.printed,
                    data: {
                      remote: true,
                      url: toggle_printed_business_invoice_path(@business, invoice),
                      method: :post
                    }
                %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
    <%= will_paginate @expenses, renderer: BootstrapPagination::Rails, class: "hidden-sm hidden-xs" %>
    <%= will_paginate @expenses, renderer: BootstrapPagination::Rails, page_links: false, class: "hidden-lg hidden-md" %>
  <% end %>
  <a class="mdc-fab fab-bottom-right fab-color" aria-label="Favorite" href="<%= new_business_invoice_path %>">
    <i class="material-icons">
      ballot
    </i>
   +
  </a>
</div>

app/views/invoices/new.html.erb
<%= render "shared/sidebar" %>
<div class="page-content-wrapper">
  <div class="document-form-container">
    <%= render 'shared/invoice-form' %>
  </div>
</div>

app/views/invoices/print.pdf.erb
<%= content_for :title, @invoice.pdf_file_name %>
<!-- Actualizar if con el estado de la factura a anulado -->
<% if false %>
  <%= content_for :body_background, cl_image_path("Default%20Pics/cancelled__invoice_pdf_background.png") %>
<% end %>

<div class="pdf-container">
  <div class="pdf-top">
    <% if @business.logo.present? %>
      <div class="bussines-logo" style="background-image: url('<%= cl_image_path @business.logo, width: 300, height: 100, crop: :fill; %>')">
      </div>
    <% end %>
    <div class="bussines-info">
      <h2 class="text-center">FACTURA DE VENTA</h2>
      <h3 class="text-center"><%= @business.name %></h3>
      <p class="text-center" >NIT <%= @business.tax_id %></p>
      <p class="text-center" ><%= @business.address %></p>
      <p class="text-center" ><%= @business.cell_phone %></p>
      <p class="text-center" ><%= @business.email %></p>
    </div>
    <div class="invoice-number-box">
      <h3 class="text-center">No. <%= @invoice.formated_number %></h3>
      <h4 class="text-center">IVA Régimen Común</h4>
      <p class="text-center"><%= @invoice.resolution_number %></p>
    </div>
  </div>
  <br>
  <br>
  <div class="pdf-center">
    <table class="benificary-info">
      <tr>
        <th colspan="1">Cliente</th>
        <td colspan="3"><%= @contact.name %></td>
        <th colspan="1" rowspan="1" class="expense-date-header">Fecha Expedición(DD/MM/AA)</th>
      </tr>
      <tr>
        <th colspan="1">Dirección</th>
        <td colspan="3"><%= @contact.address %></td>
        <td colspan="1" rowspan="2" class="text-center"><h3><%= @invoice.formated_date %></h3></td>
      </tr>
      <tr>
        <th colspan="1">Ciudad</th>
        <td colspan="3"><%= @contact.city %></td>
      </tr>
      <tr>
        <th colspan="1">Departamento</th>
        <td colspan="3"><%= @contact.province %></td>
        <th colspan="1" rowspan="1">Fecha Vencimiento (DD/MM/AA)</th>
      </tr>
      <tr>
        <th colspan="1"><%= @contact.phone_numbers_label_for_pdf %></th>
        <td colspan="3"><%= @contact.phone_numbers %></td>
        <td colspan="1" rowspan="2" class="expense-date-value"><h3><%= @invoice.formated_expiration_date %></h3></td>
      </tr>
      <tr>
        <th colspan="1"><%= @contact.tax_id_type.split("-")[0] %></th>
        <td colspan="3"><%= @contact.tax_id %></td>
      </tr>
    </table>
    <table class="expense-info">
      <thead>
        <tr>
          <th colspan="4">Item</th>
          <th colspan="1">Cantidad</th>
          <th colspan="1">Precio</th>
          <th colspan="1">Total</th>
        </tr>
      </thead>
      <tbody>
        <% @invoice.items.each do |item| %>
          <tr>
            <td colspan="4"><%= item.name %></td>
            <td colspan="1" class="concept-value"><%= item.quantity %></td>
            <td colspan="1" class="concept-value"><%= humanized_money_with_symbol item.price %></td>
            <td colspan="1" class="concept-value"><%= humanized_money_with_symbol(item.gross_total) %></td>
          </tr>
        <% end %>
        <% size = 20 - @invoice.items.size > 0 ?  20 - @invoice.items.size : 0 %>
        <% size.times do %>
          <tr>
            <td colspan="4"></td>
            <td colspan="1"></td>
            <td colspan="1"></td>
            <td colspan="1" class="concept-value"> </td>
          </tr>
        <% end %>
      </tbody>
     </table>
     <br>
    <table>
      <tr>
        <td colspan="4" rowspan="3"  class="notes-box"><%= @invoice.notes %></td>
        <td colspan="2"  class="subtotal-title">Subtotal</td>
        <td colspan="2"  class="subtotal-value"><%= humanized_money_with_symbol(@invoice.items_gross_subtotal) %></td>
      </tr>
      <tr>
        <td colspan="2"  class="subtotal-title">Descuento</td>
        <td colspan="2"  class="subtotal-value"><%= humanized_money_with_symbol(@invoice.items_discount_subtotal) %></td>
      </tr>
      <tr>
        <td colspan="2"  class="subtotal-title" >Subtotal</td>
        <td colspan="2"  class="subtotal-value"><%= humanized_money_with_symbol(@invoice.items_net_subtotal) %></td>
      </tr>
      <tr>
        <td colspan="4" rowspan="3" class="terms-and-conditions-box">
          <ul class="terms_and_conditions-list">
            <% @invoice.terms_and_conditions.split("\n").each do |line| %>
              <li><%= line %></li>
            <% end %>
          </ul>
        </td>
        <td colspan="2"  class="subtotal-title">IVA</td>
        <td colspan="2"  class="subtotal-value"><%= humanized_money_with_symbol(@invoice.items_vat_subtotal) %></td>
      </tr>
      <tr>
        <td colspan="2" class="grand-total-title">Total</td>
        <td colspan="2" class="grand-total-value"><%= humanized_money_with_symbol(@invoice.total) %></td>
      </tr>
    </table>
  </div>
  <br>
  <br>
  <br>
  <div class="pdf-bottom">
    <%= cl_image_tag  @invoice.signature?, width: 200, height: 100, class: "invoice-pdf-signature" %>
    <span class="text-center made-by">
      ELABORADO POR
    </span>
    <span class="text-center accepeted-by">ACEPTADA, FIRMA Y/O SELLO Y FECHA</span>
  </div>
</div>

app/views/invoices/show.html.erb
<%= render 'shared/sidebar' %>
<div class="page-content-wrapper">
  <div class="show-actions">
    <%= link_to print_business_invoice_path(@business, @invoice),class: "btn show-action-btn", target: :blank  do %>
      Imprimir
      <i class="material-icons"> print </i>
    <% end %>
    <%= link_to edit_business_invoice_path(@business, @invoice), class: "btn show-action-btn" do %>
      Editar
      <i class="material-icons"> create </i>
    <% end %>
    <%= link_to business_invoice_path(@business, @invoice), class: "btn show-action-btn", method: :delete, data: { confirm: '¿Estás seguro?' } do %>
      Eliminar
      <i class="material-icons"> delete </i>
    <% end %>
  </div>
  <div class="invoice-show-page-container">
    <div class="document-form-header">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <div class="bussines-logo" style="background-image: url('<%= cl_image_path @business.logo, width: 200, height: 100, crop: :fill; %>')">
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="document-header-business-info">
            <h1 class="text-center">Factura de Venta</h1>
            <p class="text-center"><%= @business.name %></p>
            <p class="text-center"><%= @business.tax_id %></p>
            <p class="text-center">Dir: <%= @business.address %></p>
            <p class="text-center"><%= @business.cell_phone %></p>
            <p class="text-center"><%= @business.email %></p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="document-header-dian-info">
            <div class="invoice-header-number-container">
              <p>No. </p>
              <p><%= @invoice.number %></p>
            </div>
            <p class="text-center text-bold">IVA Régimen Común</p>
            <p class="text-center"><%= @invoice.resolution_number %></p>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="table-container show-table">
      <div class="table">
        <div class="table-row">
          <div class="table-header">Beneficiario</div>
          <div class="table-data"><%= @invoice.contact.name %></div>
          <div class="table-header">Fecha</div>
          <div class="table-data"><%= @invoice.date %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Identificación</div>
          <div class="table-data"><%= @invoice.contact.tax_id %></div>
          <div class="table-header">Vencimiento</div>
          <div class="table-data"><%= @invoice.expiration_date %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Teléfono</div>
          <div class="table-data"><%= @invoice.contact.phone %></div>
          <div class="table-header">Plazo</div>
          <div class="table-data"><%= pluralize(@invoice.term, "dia", "días") %></div>
        </div>
      </div>
    </div>
    <br>
    <div class="items-table-container">
      <div class="table"
           id="items-table"
           data-controller="invoice-form"
      >
        <div class="table-row" >
          <div class="table-header">Item</div>
          <div class="table-header">Cantidad</div>
          <div class="table-header">Precio Unitario</div>
          <div class="table-header">IVA(%)</div>
          <div class="table-header">Descuento(%)</div>
          <div class="table-header">Total</div>
        </div>
        <% @items.each do |item| %>
          <%= render 'shared/edit-item-fields',
              item: item,
              invoice_id: nil,
              items_delete_params: nil
          %>
        <% end %>
      </div>

    </div>
    <br>
    <br>
    <br>
    <br>
    <div class="document-form-bottom">
      <div class="row">
        <div class="col-xs-12 col-sm-8">
          <div class="signature">
            <% if @invoice.signature? %>
              <%= cl_image_tag  @invoice.signature?, width: 200, height: 100%>
            <% end %>
            <p class="signature-by">ELABORADO POR</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="totals">
            <div class="totals-item">
              <p>Subotal: </p>
              <p><%= humanized_money_with_symbol @invoice.items_gross_subtotal%></p>
            </div>
            <div class="totals-item">
              <p>Descuento: </p>
              <p><%= humanized_money_with_symbol @invoice.items_discount_subtotal %></p>
            </div>
            <div class="totals-item">
              <p>Subtotal: </p>
              <p><%= humanized_money_with_symbol @invoice.items_net_subtotal %></p>
            </div>
            <div class="totals-item">
              <p>IVA: </p>
              <p><%= humanized_money_with_symbol @invoice.items_vat_subtotal %></p>
            </div>
            <hr>
            <div class="totals-item totals-item--grand-total">
              <p>TOTAL: </p>
              <p><%= humanized_money_with_symbol @invoice.total %></p>
            </div>
          </div>
        </div>
      </div>
      <br>
      <br>
      <br>
      <div class="row">
        <div class="col-xs-12 col-sm-7">
          <p class="bottom-notes-label">Términos y condiciones</p>
            <ul class="bottom-notes list-no-style">
              <% @invoice.terms_and_conditions.split("\n").each do |line| %>
                <li><%= line %></li>
              <% end %>
            </ul>
          <!-- <p class="bottom-notes"><%#= @invoice.terms_and_conditions %></p> -->
        </div>
        <div class="col-xs-12 col-sm-5">
          <p class=" bottom-notes-label">Notas</p>
          <p class="bottom-notes"><%= @invoice.notes %></p>
        </div>
      </div>
    </div>

  </div>
</div>