config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'businesses#index', as: :authenticated_root
  end
  unauthenticated :user do
    root to: 'pages#home'
  end
  devise_for :users,
  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :businesses do
    resources :items, only: :index, to: "businesses#items"
    resources :contacts do
      member do
        get '/invoices', to: "contacts#invoices", defaults: { format: 'pdf' }
      end
    end

    resources :expenses do
      member do
        get '/print', to: "expenses#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :expenses do
      member do
        get '/print', to: "expenses#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :invoices do
      member do
        get '/print', to: "invoices#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :payments do
      member do
        get '/print', to: "payments#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :invoice_equivalents do
      member do
        get '/print', to: "invoice_equivalents#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :attachments, only: :show
    resources :exports, only: [:new, :create]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_budget.html.erb
<svg width="70" height="70" viewBox="0 0 512 512" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M255.996 88.274L291.305 61.792V0H255.996L238.341 17.655L220.686 0H167.721L150.066 17.655L132.411 0H97.1016V61.792L132.411 88.274H255.996Z" fill="#E6E6E6"/>
<path d="M329.802 194.618C308.254 166.414 279.194 144.858 245.959 132.411H142.449C54.218 163.466 0 270.79 0 361.448C0 468.737 86.95 511.991 194.204 511.991C217.853 512.168 241.448 509.749 264.567 504.779V194.204L329.802 194.618Z" fill="#E6E6E6"/>
<path d="M255.987 88.2739H132.403V132.411H255.987V88.2739Z" fill="#2996BF"/>
<path d="M255.996 476.681C148.743 476.681 61.792 433.427 61.792 326.138C61.792 257.761 92.688 179.867 145.767 132.411H142.448C54.218 163.466 0 270.79 0 361.448C0 468.737 86.95 511.991 194.204 511.991C217.853 512.168 241.448 509.749 264.567 504.779V476.478C261.707 476.54 258.882 476.681 255.996 476.681Z" fill="#CCCCCC"/>
<path d="M326.359 194.601H329.802C328.69 193.206 327.498 191.891 326.359 190.523V194.601Z" fill="#CCCCCC"/>
<path d="M194.195 432.544C252.698 432.544 300.124 385.118 300.124 326.615C300.124 268.112 252.698 220.686 194.195 220.686C135.692 220.686 88.2656 268.112 88.2656 326.615C88.2656 385.118 135.692 432.544 194.195 432.544Z" fill="#FAD87C"/>
<path opacity="0.3" d="M231.279 395.469C172.868 395.557 125.438 348.278 125.35 289.858C125.324 270.747 130.47 251.988 140.242 235.578C89.9171 265.335 73.2421 330.252 102.999 380.577C132.756 430.902 197.673 447.577 247.998 417.82C263.349 408.745 276.166 395.928 285.241 380.577C268.928 390.323 250.275 395.469 231.279 395.469Z" fill="#E97424"/>
<path d="M511.982 194.204H264.814V511.992H511.982V194.204Z" fill="#2996BF"/>
<path d="M511.982 194.204H264.814V264.823H511.982V194.204Z" fill="#E3646A"/>
<path d="M335.434 300.133H300.124V335.443H335.434V300.133Z" fill="#FAD87C"/>
<path d="M406.053 300.133H370.743V335.443H406.053V300.133Z" fill="#FAD87C"/>
<path d="M476.673 300.133H441.363V335.443H476.673V300.133Z" fill="#FAD87C"/>
<path d="M335.434 370.752H300.124V406.062H335.434V370.752Z" fill="#FAD87C"/>
<path d="M406.053 370.752H370.743V406.062H406.053V370.752Z" fill="#FAD87C"/>
<path d="M335.434 441.372H300.124V476.682H335.434V441.372Z" fill="#FAD87C"/>
<path d="M406.053 441.372H370.743V476.682H406.053V441.372Z" fill="#FAD87C"/>
<path d="M476.673 370.752H441.363V476.681H476.673V370.752Z" fill="#FAD87C"/>
<path d="M194.203 388.407C174.703 388.407 158.893 372.597 158.893 353.097H176.548C176.548 362.851 184.449 370.752 194.203 370.752C203.957 370.752 211.858 362.851 211.858 353.097C211.858 346.353 207.541 340.359 201.141 338.223L181.677 331.752C168.065 327.224 158.885 314.477 158.893 300.132C158.893 280.632 174.703 264.822 194.203 264.822C213.703 264.822 229.513 280.632 229.513 300.132H211.858C211.858 290.378 203.957 282.477 194.203 282.477C184.449 282.477 176.548 290.378 176.548 300.132C176.548 306.876 180.865 312.87 187.265 315.006L206.729 321.477C220.341 326.005 229.521 338.752 229.513 353.097C229.513 372.597 213.703 388.407 194.203 388.407Z" fill="#006684"/>
<path d="M203.021 247.168H185.366V273.65H203.021V247.168Z" fill="#006684"/>
<path d="M203.021 379.58H185.366V406.062H203.021V379.58Z" fill="#006684"/>
<path d="M485.5 220.686H467.845V238.341H485.5V220.686Z" fill="#006684"/>
<path d="M450.189 220.686H432.534V238.341H450.189V220.686Z" fill="#006684"/>
<path d="M414.881 220.686H397.226V238.341H414.881V220.686Z" fill="#006684"/>
</svg>

app/views/shared/_building-form.html.erb
<%= simple_form_for(business) do |f| %>
  <i class="fas fa-building"></i>
  <%= f.input :name, label: "Nombre de la empresa"%>
  <%= f.input :address, label: "Dirección" %>
  <%= f.input :cell_phone, label: "Teléfono de contacto" %>
  <%= f.input :email, label: "Email de contacto" %>
  <%= f.input :tax_id, label: "NIT" %>
  <%= f.input :logo, label: "Logo" %>
  <%= f.input :logo_cache, as: :hidden %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
  <span class="new-building-form-btns">
    <%= link_to "cancelar", businesses_path, class:"form-btn--no-background" %>
    <% if action_name == "new" || action_name == "create" %>
      <%= f.submit "Crear", class:"btn form-btn" %>
    <% else %>
      <%= f.submit "Editar", class:"btn form-btn" %>
    <% end %>
  </span>
<% end %>

app/views/shared/_business-form.html.erb
<%= simple_form_for(business) do |f| %>
  <div class="basic-info">
    <h4>Información Básica</h4>
    <%= f.input :name, label: "Nombre de la empresa"%>
    <%= f.input :address, label: "Dirección" %>
    <%= f.input :cell_phone, label: "Teléfono de contacto" %>
    <%= f.input :email, label: "Email de contacto" %>
    <%= f.input :tax_id, label: "NIT" %>
  </div>
  <hr>
  <div class="photos">
    <h4>Logo y Firma</h4>
    <% if @business.logo.file  %>
      <div class="bussines-logo" style="background-image: url('<%= cl_image_path @business.logo, width: 200, height: 100, crop: :fill; %>')">
      </div>
    <% end %>
    <%= f.input :logo, label: "Logo" %>
    <%= f.input :logo_cache, as: :hidden %>
    <% if @business.signature.file  %>
      <%= cl_image_tag  @business.signature, width: 200, height: 100%>
    <% end %>
    <%= f.input :signature, label: "Firma por defecto" %>
    <%= f.input :signature_cache, as: :hidden %>
  </div>
  <hr>
  <div class="invoice-texts">
    <h4>Textos por defecto en la factura</h4>
    <%= f.input :invoice_resolution_number,
                label: "Resolución de facturación",
                input_html: {
                  placeholder: Business::INVOICE_RESOLUTION_NUMBER
                }
    %>
    <%= f.input :invoice_terms_and_conditions,
                label: "Términos y condiciones",
                input_html: {
                  placeholder: Business::INVOICE_TERMS_AND_CONDITIONS
                }
    %>
    <%= f.input :invoice_notes,
                label: "Notas",
                input_html: {
                  placeholder: Business::INVOICE_NOTES
                }

    %>

  </div>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
  <span class="new-business-form-btns">
    <%= link_to "cancelar", businesses_path, class:"form-btn--no-background" %>
    <% if action_name == "new" || action_name == "create" %>
      <%= f.submit "Crear", class:"btn form-btn" %>
    <% else %>
      <%= f.submit "Editar", class:"btn form-btn" %>
    <% end %>
  </span>
<% end %>

app/views/shared/_businesses-icon.html.erb
<svg width="58" height="59" viewBox="0 0 58 59" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M58 48H0V59H58V48Z" fill="#ECF0F1"/>
<path d="M42 0H16V48H42V0Z" fill="#556080"/>
<path d="M0 3V19V37V48H16V37V19V3H0Z" fill="#8697CB"/>
<path d="M42 3V19V37V48H58V37V19V3H42Z" fill="#8697CB"/>
<path d="M27 5H20V10H27V5Z" fill="white"/>
<path d="M38 5H31V10H38V5Z" fill="white"/>
<path d="M54 9H46V14H54V9Z" fill="white"/>
<path d="M54 18H46V23H54V18Z" fill="white"/>
<path d="M12 9H4V14H12V9Z" fill="white"/>
<path d="M12 18H4V23H12V18Z" fill="white"/>
<path d="M27 14H20V19H27V14Z" fill="white"/>
<path d="M38 14H31V19H38V14Z" fill="white"/>
<path d="M27 23H20V28H27V23Z" fill="white"/>
<path d="M38 23H31V28H38V23Z" fill="white"/>
<path d="M38 59H20L22 48H36L38 59Z" fill="#ED7161"/>
<path d="M37 34H21V48H37V34Z" fill="#D0E8F9"/>
<path d="M37 33H21C20.448 33 20 33.448 20 34V48H38V34C38 33.448 37.552 33 37 33Z" fill="#3D324C"/>
<path d="M36 35H22V48H36V35Z" fill="#D0E8F9"/>
<path d="M30 35H28V48H30V35Z" fill="#3D324C"/>
<path d="M8 45C12.4183 45 16 41.4183 16 37C16 32.5817 12.4183 29 8 29C3.58172 29 0 32.5817 0 37C0 41.4183 3.58172 45 8 45Z" fill="#A4E869"/>
<path d="M50 45C54.4183 45 58 41.4183 58 37C58 32.5817 54.4183 29 50 29C45.5817 29 42 32.5817 42 37C42 41.4183 45.5817 45 50 45Z" fill="#A4E869"/>
<path d="M10.2933 37.293L8.00025 39.586L5.70725 37.293C5.31625 36.902 4.68425 36.902 4.29325 37.293C3.90225 37.684 3.90225 38.316 4.29325 38.707L7.00025 41.414V58C7.00025 58.552 7.44825 59 8.00025 59C8.55225 59 9.00025 58.552 9.00025 58V41.414L11.7072 38.707C12.0982 38.316 12.0982 37.684 11.7072 37.293C11.3162 36.902 10.6843 36.902 10.2933 37.293Z" fill="#7F6E5D"/>
<path d="M53.7073 37.293C53.3163 36.902 52.6843 36.902 52.2933 37.293L50.0003 39.586L47.7073 37.293C47.3163 36.902 46.6842 36.902 46.2932 37.293C45.9022 37.684 45.9022 38.316 46.2932 38.707L49.0003 41.414V58C49.0003 58.552 49.4483 59 50.0003 59C50.5523 59 51.0003 58.552 51.0003 58V41.414L53.7073 38.707C54.0983 38.316 54.0983 37.684 53.7073 37.293Z" fill="#7F6E5D"/>
</svg>

app/views/shared/_centralized-icon.html.erb
<svg width="70" height="70" viewBox="0 0 70 70" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M53.7076 30.625L43.0266 34.3125L41.6387 30.625L51.8973 27.0837L53.7076 30.625Z" fill="#55D08F"/>
<path d="M18.7069 50L29.5689 42.5L27.201 38.7175L16.5586 46.0675L18.7069 50Z" fill="#55D08F"/>
<path d="M35.0009 46.25C40.3333 46.25 44.656 41.7728 44.656 36.25C44.656 30.7272 40.3333 26.25 35.0009 26.25C29.6685 26.25 25.3457 30.7272 25.3457 36.25C25.3457 41.7728 29.6685 46.25 35.0009 46.25Z" fill="#83D8EF"/>
<path d="M16.9959 13.6462L31.9518 29.3437C32.7852 30.2067 32.7852 31.6061 31.952 32.4692C31.8527 32.572 31.7439 32.6644 31.6271 32.745C30.781 33.3298 29.6536 33.2142 28.9346 32.4687L14.0801 16.9787L16.9959 13.6462Z" fill="#55D08F"/>
<path d="M44.6559 54.0625L37.3433 43.1325C36.7109 42.0839 36.9979 40.7044 37.9914 40.0188C39.0055 39.318 40.376 39.6014 41.0527 40.6517C41.0528 40.652 41.053 40.6523 41.0533 40.6525L48.2765 51.6663L44.6559 54.0625Z" fill="#55D08F"/>
<path d="M9.65517 20C14.9876 20 19.3103 15.5228 19.3103 10C19.3103 4.47715 14.9876 0 9.65517 0C4.32277 0 0 4.47715 0 10C0 15.5228 4.32277 20 9.65517 20Z" fill="#FFBC44"/>
<path d="M60.3446 36.25C65.677 36.25 69.9998 31.7728 69.9998 26.25C69.9998 20.7272 65.677 16.25 60.3446 16.25C55.0122 16.25 50.6895 20.7272 50.6895 26.25C50.6895 31.7728 55.0122 36.25 60.3446 36.25Z" fill="#FBCC34"/>
<path d="M10.8622 62.5C16.1946 62.5 20.5174 58.0228 20.5174 52.5C20.5174 46.9772 16.1946 42.5 10.8622 42.5C5.5298 42.5 1.20703 46.9772 1.20703 52.5C1.20703 58.0228 5.5298 62.5 10.8622 62.5Z" fill="#FFBC44"/>
<path d="M49.4833 70C54.8157 70 59.1385 65.5228 59.1385 60C59.1385 54.4772 54.8157 50 49.4833 50C44.1509 50 39.8281 54.4772 39.8281 60C39.8281 65.5228 44.1509 70 49.4833 70Z" fill="#83D8EF"/>
</svg>

app/views/shared/_contact-form.html.erb
<%= simple_form_for [@business, @contact]  do |f| %>
  <%= f.input :name, label: "Nombre"%>
  <%= f.input :tax_id_type, label: "Tipo de Identificación", collection: Contact.tax_id_types.keys%>
  <%= f.input :tax_id, label: "Número de Identificación"%>
  <%= f.input :phone, label: "Teléfono"%>
  <%= f.input :cell_phone, label: "Celular"%>
  <%= f.input :email, label: "Correo Electrónico"%>
  <%= f.input :province, label: "Departamento"%>
  <%= f.input :city, label: "Ciudad"%>
  <%= f.input :address, label: "Dirección"%>
  <%= f.input :account_type, label: "Tipo de Cuenta", collection: Contact.account_types.keys %>
  <%= f.input :account_bank, label: "Banco", collection: Contact.account_banks.keys %>
  <%= f.input :account_number, label: "Número de cuenta" %>
  <%= f.input :client, label: "Agregar como Cliente"%>
  <%= f.input :provider, label: "Agregar como Proveedor"%>
  <%= f.input :business_id, as: :hidden, input_html: { value: @business.id } %>
  <span class="new-property-form-btns">
    <%= link_to "cancelar", :back, class:"form-btn--no-background" %>
    <% if action_name == "new" || action_name == "create" %>
      <%= f.submit "Crear", class:"btn form-btn" %>
    <% else %>
      <%= f.submit "Editar", class:"btn form-btn" %>
    <% end %>
  </span>
<% end %>

app/views/shared/_edit-item-fields.html.erb
<div class="table-row" data-controller="item-form" data-target="invoice-form.row">

  <div class="table-data">
    <%= item.name %>
  </div>

  <div class="table-data">
    <input
      class="item-quantity no-style-input text-center"
      data-target="invoice-form.quantity"
      type="number"
      disabled="disabled"
      value="<%= item.quantity %>"
    >
  </div>

  <div class="table-data">
    <input
      class="item-price no-style-input text-center"
      data-controller="cleave"
      type="text"
      value="<%= item.price %>"
      disabled="disabled"
    >
  </div>

  <div class="table-data">
    <input
      class="item-vat no-style-input text-center"
      value="<%= item.vat %>"
      data-target="invoice-form.vat"
      type="number"
      disabled="disabled"
    >
  </div>

  <div class="table-data">
    <input
      class="item-discount no-style-input text-center"
      value="<%= item.discount %>"
      data-target="invoice-form.discount"
      type="number"
      disabled="disabled"
    >
  </div>

  <div class="table-data">
    <input
      type="text"
      class="item-total no-style-input text-center"
      value="<%= item.gross_total %>"
      data-controller="cleave"
      disabled="disabled">
  </div>
  <% if  items_delete_params %>
    <div class="table-data">
      <%= link_to business_invoice_path(invoice_id, items_delete_params), class: "delete-attachement", remote: true,  method: :patch, data: { confirm: "¿Estás Seguro?", action: "ajax:success->item-form#deleteItemRow" } do%>
        <i class="material-icons"> delete </i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_export-form.html.erb
<%= simple_form_for :export, url: business_exports_path(@business), method: :post  do |f| %>
  <%= f.input :dates,
              as: :string,
              placeholder: "Exportar todo",
              label: "Rango de Fechas a Exportar",
              input_html: {
                required: true,
                class: "datepicker-expense",
                  data: { controller: "flatpickr", "flatpickr-type": "export"}
              }
  %>
  <br>
  <h5 class="text-center">¿Qué quieres incluir en el reporte?</h5>
  <hr>
  <%= f.input :expense,
              label: "Comprobantes de Egreso:",
              as: :boolean,
              input_html: {
                checked: true
              }
  %>
  <%= f.input :invoice,
              label: "Factuas de Venta:",
              as: :boolean,
              input_html: {
                checked: true
              }
  %>
  <%= f.input :invoice_equivalent,
              label: "Documentos Equivalentes:",
              as: :boolean,
              input_html: {
                checked: true
              }
  %>
  <%= f.input :payment,
              label: "Recibos de Caja:",
              as: :boolean,
              input_html: {
                checked: true
              }
  %>
  <%= f.input :contact,
              label: "Contactos Creados:",
              as: :boolean,
              input_html: {
                checked: true
              }
  %>
  <span class="new-property-form-btns">
    <%= link_to "cancelar", :back, class:"form-btn--no-background" %>
    <%= f.submit "Enviar", class:"btn form-btn" %>
  </span>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible <%= "alert-with-margin" if render_blue_sidebar %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible <%= "alert-with-margin" if render_blue_sidebar %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_item-fields.html.erb
<div  class="table-row nested-fields"
      data-controller="item-form"
      data-target="invoice-form.row"
      data-action="keyup->item-form#recalculateTotal change->item-form#recalculateTotal keyup->invoice-form#calculateTotals change->invoice-form#calculateTotals"
>
  <div class="table-data min-width-200">
    <% if f.object.name %>
      <%= f.input :name, label: false %>
    <% else %>
    <%= f.input :name,
                collection: [ ["" ,"", data: { placeholder: true }] ],
                label: false,
                input_html: {
                  data: {
                    controller: "slim-select",
                    slim_select_type: "itemSelector",
                    slim_select_fetch_url: business_items_path(@business)
                  }
                }
    %>
    <% end %>
  </div>
  <div class="table-data min-width-100">
    <%= f.input :quantity,
                label: false,
                input_html: {
                  min: '0',
                  class: "item-quantity",
                  data: {
                    action: "focus->invoice-form#calculateTotals",
                    target: "item-form.quantity invoice-form.quantity"
                  }
                }
    %>
  </div>
  <div class="table-data min-width-200">
    <%= f.input :price,
                label: false,
                input_html: {
                  class: "amount-input item-price",
                  min: '0',
                  data: {
                    controller: "cleave",
                    action: "focus->cleave#mountCleave",
                    target: "item-form.price invoice-form.price"
                  }
                }
    %>
  </div>
  <div class="table-data min-width-100">
    <%= f.input :vat,
                label: false,
                input_html: {
                  step: 0.01,
                  value: f.object.vat?,
                  class: "item-vat",
                  data: { target: "item-form.vat invoice-form.vat" }
                }
    %>
  </div>
  <div class="table-data min-width-100">
    <%= f.input :discount,
                label: false,
                input_html: {
                  step: 0.001,
                  value: f.object.discount?,
                  class: "item-discount",
                  data: { target: "item-form.discount invoice-form.discount" }
                }
    %>
  </div>
  <div class="table-data min-width-200">
    <%= f.input :fake_total,
                as: :fake,
                label: false,
                disabled: true,
                input_html: {
                  class: "item-total",
                  value: f.object.gross_total?,
                  data: {
                    controller: "cleave",
                    action: "focus->cleave#mountCleave",
                    target: "item-form.total"
                  }
                }
    %>
  </div>
  <div class="table-data">
    <%= f.input :_destroy, as: :hidden %>
    <%= link_to "#", data: { action: "click->nested-form#remove_association click->invoice-form#setCalulationsTimer" }  do %>
      <button class="close-form-btn no-style-btn">
        <i class="material-icons">
          clear
        </i>
      </button>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% unless devise_controller? %>
  <div class="navbar-wagon <%= navbar_color %> <%= do_not_render_navbar_web %>" data-controller="navbar" data-action="scroll@window->navbar#scroll" >
    <div class="navbar-wagon-item navbar-wagon-dropicon hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown" data-controller="sidebar" data-action="click->sidebar#toggle" data-sidebar-selector="#mySidenav"></i>
        <ul class="dropdown-menu dropdown-menu-left navbar-wagon-dropdown-menu <%= "hidden" unless render_navbar_dropdown %>">
          <% if current_user %>
            <li><%= link_to "Inicio", root_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Cerrar Sesión", destroy_user_session_path , method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <% else %>
            <li><a href="#features" class="navbar-wagon-item navbar-wagon-link">Caracteristicas</a></li>
            <li><a href="#contact" class="navbar-wagon-item navbar-wagon-link">Contacto</a></li>

            <li><%= link_to "Iniciar Sesión", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"  %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <a href="/" class="navbar-wagon-brand <%= "hidden" unless action_name == "home" %>" id="white-logo" data-target="navbar.whiteLogo">
      <%= render 'shared/sidebar-logo' %>
    </a>
    <a href="/" class="navbar-wagon-brand <%= "hidden" if action_name == "home" %>" id="color-logo" data-target="navbar.colorLogo">
      <%= render 'shared/navbar-logo' %>
    </a>
    <div class="navbar-wagon-item navbar-wagon-invisible hidden-md hidden-lg"></div>

    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <% if current_user %>
        <%= link_to "Cerrar Sesión", destroy_user_session_path , method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <a href="#features" class="navbar-wagon-item navbar-wagon-link">Caracteristicas</a>
        <a href="#contact" class="navbar-wagon-item navbar-wagon-link">Contacto</a>
        <%= link_to "Iniciar Sesión", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"  %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/shared/_tawk-support-chat.html.erb
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5b9c1a4ac666d426648ac747/1cnmisu8k';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->