config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'businesses#index', as: :authenticated_root
  end
  unauthenticated :user do
    root to: 'pages#home'
  end
  devise_for :users,
  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :businesses do
    resources :items, only: :index, to: "businesses#items"
    resources :contacts do
      member do
        get '/invoices', to: "contacts#invoices", defaults: { format: 'pdf' }
      end
    end

    resources :expenses do
      member do
        get '/print', to: "expenses#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :expenses do
      member do
        get '/print', to: "expenses#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :invoices do
      member do
        get '/print', to: "invoices#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :payments do
      member do
        get '/print', to: "payments#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :invoice_equivalents do
      member do
        get '/print', to: "invoice_equivalents#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :attachments, only: :show
    resources :exports, only: [:new, :create]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/invoice_equivalent.rb
class InvoiceEquivalent < ApplicationRecord
  before_validation :add_invoice_equivalent_number, on: :create
  belongs_to :business
  belongs_to :contact

  monetize :amount_cents
  monetize :retention_cents

  enum retention_type: ["Arrendamiento de bienes muebles - (4%)",
                        "Arrendamiento de bienes raíces - (3.5%)",
                        "Compras - (2.5%)",
                        "Compras - (3.5%)",
                        "Honorarios y comisiones - (10%)",
                        "Honorarios y comisiones - (11%)",
                        "Servicios de aseo y vigilancia - (2%)",
                        "Servicios de hoteles y restaurantes - (3.5%)",
                        "Servicios en general - (4%)",
                        "Servicios en general - (6%)",
                        "ReteICA - (0%)",
                        "ReteIVA - (15%)",
                        "Transporte de carga - (1%)",
                        "Servicios tecnológicos - (3.5%)"]

  validates :date, :description, :number, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true

  def formated_number
    format("%03d", number)
  end

  def pdf_file_name
    "#{formated_number} DE #{description}"
  end

  def formated_date
    date.strftime("%d/%m/%Y")
  end

  def total
    amount - retention
  end

  def retention_full_name
    return unless retention

    if retention_type && retention
      "#{ActionController::Base.helpers.humanized_money_with_symbol retention} - #{retention_type}"
    elsif retention
      "#{ActionController::Base.helpers.humanized_money_with_symbol retention}"
    end
  end

  private

  def add_invoice_equivalent_number
    self.number = business.invoice_equivalents.size + 1
  end
end

app/controllers/invoice_equivalents_controller.rb
class InvoiceEquivalentsController < ApplicationController
  before_action :set_business, except: :update
  before_action :set_invoice_equivalent, only: %i[show edit update destroy print toggle_printed]

  def index
    @invoice_equivalents = policy_scope(InvoiceEquivalent.where(business: @business).order(number: :desc).includes(:contact).paginate(page: params[:page]))
  end

  def show
    @attachments = @invoice_equivalent.attachments
    authorize @invoice_equivalent
  end

  def new
    @invoice_equivalent = InvoiceEquivalent.new
    authorize @business, :business_of_current_user?
  end

  def create
    @invoice_equivalent = InvoiceEquivalent.new(invoice_equivalent_params)
    authorize @business, :business_of_current_user?
    if @invoice_equivalent.save
      flash[:notice] = "Documento equivalente a factura de venta creado existosamente"
      redirect_to business_invoice_equivalent_path @business, @invoice_equivalent
    else
      render :new
    end
  end

  def edit
    authorize @invoice_equivalent
  end

  def update
    @business = Business.find(invoice_equivalent_params[:business_id])
    authorize @business, :business_of_current_user?
    if @invoice_equivalent.update(invoice_equivalent_params)
      flash[:notice] = "Documento equivalente a factura de venta actualizado existosamente"
      redirect_to business_invoice_equivalent_path @business, @invoice_equivalent
    else
      render 'edit'
    end
  end

  def destroy
    authorize @invoice_equivalent
    @invoice_equivalent.destroy
    flash[:notice] = "Documento Equivalente a factura de venta eliminado existosamente"
    redirect_to business_invoice_equivalents_path(@business)
  end

  def print
    authorize @invoice_equivalent
    @contact = @invoice_equivalent.contact
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: @invoice_equivalent.pdf_file_name, layout: 'pdf.html', show_as_html: params.key?('debug')   # Excluding ".pdf" extension.
      end
    end
  end

  def toggle_printed
    @invoice_equivalent.update(printed: !@invoice_equivalent.printed)
  end

  private

  def invoice_equivalent_params
    strong_params = params.require(:invoice_equivalent).permit(
                      :business_id,
                      :contact_id,
                      :date,
                      :number,
                      :observation,
                      :retention_type,
                      :description,
                      :amount,
                      :retention,
                      attachments_attributes: [:id, :file, "@original_filename", "@content_type", "@headers", "_destroy"]
                    )
    # strong_params[:amount] = strong_params[:amount].gsub(",", "") if strong_params[:amount]
    strong_params[:attachments_attributes].each { |attachment| attachment[:name] = attachment[:file].original_filename } if strong_params[:attachments_attributes].is_a?(Array)
    strong_params
  end

  def set_invoice_equivalent
    @invoice_equivalent = InvoiceEquivalent.includes(:contact).find(params[:id])
  end
end

app/views/invoice_equivalents/edit.html.erb
<%= render "shared/sidebar" %>
<div class="page-content-wrapper">
  <div class="form-container">
    <div class="new-property-form-container new-owner-form-container">
      <div class="new-property-form-heading">
        <h1>Edita un documento equivalente</h1>
      </div>
      <%= render 'shared/invoice-equivalent-form' %>
    </div>
  </div>
</div>

app/views/invoice_equivalents/index.html.erb
<%= render 'shared/sidebar' %>
<div class="page-content-wrapper">
  <% if @invoice_equivalents.size == 0 %>
    <h3 class="alert alert-blue property-title text-center">
      <i class="material-icons">
       info
      </i>
      Aún no tienes ningún documento equivalente a factura de venta, agrega uno para comenzar
    </h3>
  <% else %>
    <h1 class="app-index-title">Lista de Documentos Equivalentes</h1>
    <div class="table-container table-container--no-margin-bottom">
      <div class="table">
        <div class="table-row">
          <div class="table-header">Número</div>
          <div class="table-header">Beneficiario</div>
          <div class="table-header">Detalle</div>
          <div class="table-header">Fecha</div>
          <div class="table-header">Valor Operación</div>
          <div class="table-header">Rte Fuente</div>
          <div class="table-header">Total a Pagar</div>
          <div class="table-header">Acciones</div>
          <div class="table-header">Impreso</div>
        </div>
        <% @invoice_equivalents.each do |invoice_equivalent| %>
            <div class="table-row-link table-row"
                 data-controller="table-row"
                 data-table-row-location="<%= business_invoice_equivalent_path(@business, invoice_equivalent)%>"
            >
              <div class="table-data" data-action="click->table-row#visitLocation"><%= invoice_equivalent.formated_number %></div>
              <div class="table-data" data-action="click->table-row#visitLocation"><%= invoice_equivalent.contact.name %></div>
              <div class="table-data" data-action="click->table-row#visitLocation"><%= invoice_equivalent.description %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= invoice_equivalent.date %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= humanized_money_with_symbol invoice_equivalent.amount %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= humanized_money_with_symbol invoice_equivalent.retention %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= humanized_money_with_symbol invoice_equivalent.total %></div>
              <div class="table-data white-space-no-wrap">
                <%= link_to print_business_invoice_equivalent_path(@business, invoice_equivalent), target: :blank  do %>
                  <i class="material-icons"> print </i>
                <% end %>
                <%= link_to edit_business_invoice_equivalent_path(@business, invoice_equivalent), class: "edit-property" do %>
                  <i class="material-icons"> create </i>
                <% end %>
                <%= link_to business_invoice_equivalent_path(@business, invoice_equivalent), class: "destroy-property", method: :delete, data: { confirm: '¿Estás seguro?' } do %>
                  <i class="material-icons"> delete </i>
                <% end %>
              </div>
              <div class="table-data">
                <%= check_box_tag 'printed', invoice_equivalent.id, invoice_equivalent.printed,
                    data: {
                      remote: true,
                      url: toggle_printed_business_invoice_equivalent_path(@business, invoice_equivalent),
                      method: :post
                    }
                %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
    <%= will_paginate @invoice_equivalents, renderer: BootstrapPagination::Rails, class: "hidden-sm hidden-xs" %>
    <%= will_paginate @invoice_equivalents, renderer: BootstrapPagination::Rails, page_links: false, class: "hidden-lg hidden-md" %>
  <% end %>
  <a class="mdc-fab fab-bottom-right fab-color" aria-label="Favorite" href="<%= new_business_invoice_equivalent_path %>">
    <i class="material-icons">
      description
    </i>
   +
  </a>
</div>

app/views/invoice_equivalents/new.html.erb
<%= render "shared/sidebar" %>
<div class="page-content-wrapper">
  <div class="form-container">
    <div class="new-property-form-container new-expense-form-container">
      <div class="new-property-form-heading">
        <h1>Nuevo documento equivalente en <%= @business.name %></h1>
      </div>
      <%= render 'shared/invoice-equivalent-form' %>
    </div>
  </div>
</div>

app/views/invoice_equivalents/print.pdf.erb
<%= content_for :title, @invoice_equivalent.pdf_file_name %>

<div class="pdf-container">
  <div class="pdf-top">
    <% if @business.logo.present? %>
      <div class="bussines-logo" style="background-image: url('<%= cl_image_path @business.logo, width: 300, height: 100, crop: :fill; %>')">
      </div>
    <% end %>
    <div class="bussines-info">
      <h3 class="text-center"><%= @business.name %></h3>
      <p class="text-center" >NIT <%= @business.tax_id %></p>
      <p class="text-center" ><%= @business.address %></p>
      <p class="text-center" ><%= @business.cell_phone %></p>
      <p class="text-center" ><%= @business.email %></p>
      <p class="text-center" >Decreto N. 522/2003 Art.03</p>
      <p class="text-center" ><i>Para personas naturales no comerciantes o inscritas en Régimen Simplificado</i></p>
    </div>
    <div class="expense-number-box">
      <h4 class="text-center">Documento Equivalente a Factura De Venta</h4>
      <h3 class="text-center">No. <%= @invoice_equivalent.formated_number %></h3>
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="pdf-center">
    <table class="benificary-info">
      <tr>
        <th colspan="1">Beneficiario</th>
        <td colspan="3"><%= @contact.name %></td>
        <th colspan="1" rowspan="1" class="expense-date-header">Fecha (DD/MM/AA)</td>
      </tr>
      <tr>
        <th colspan="1">Dirección</th>
        <td colspan="3"><%= @contact.address %></td>
        <td rowspan="4" class="expense-date-value"><h3><%= @invoice_equivalent.formated_date %></h3></td>
      </tr>
      <tr>
        <th colspan="1">Ciudad</th>
        <td colspan="3"><%= @contact.city %></td>
      </tr>
      <tr>
        <th colspan="1"><%= @contact.phone_numbers_label_for_pdf %></th>
        <td colspan="1"><%= @contact.phone_numbers %></td>
      </tr>
      <tr>
        <th colspan="1"><%= @contact.tax_id_type.split("-")[0] %></th>
        <td colspan="1"><%= @contact.tax_id %></td>
      </tr>
    </table>
    <table class="expense-info">
      <thead>
        <tr>
          <th colspan="4">Concepto</th>
          <th colspan="1">Cantidad</th>
          <th colspan="1">Valor Unitario</th>
          <th colspan="1">Valor Total</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="4"><%= @invoice_equivalent.description %></td>
          <td colspan="1" class="concept-value">1</td>
          <td colspan="1" class="concept-value"><%= humanized_money_with_symbol(@invoice_equivalent.amount) %></td>
          <td colspan="1" class="concept-value"><%= humanized_money_with_symbol(@invoice_equivalent.amount) %></td>
        </tr>
        <% 19.times do %>
          <tr>
            <td colspan="4"> </td>
            <td colspan="1"> </td>
            <td colspan="1"> </td>
            <td colspan="1" class="concept-value"> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
     <br>
    <table>
      <tr>
        <td colspan="4" rowspan="3"  class="notes-box">Observaciones: <%= @invoice_equivalent.observation %></td>
        <td colspan="1"  class="subtotal-title">Valor de la operación</td>
        <td colspan="1"  class="subtotal-value"><%= humanized_money_with_symbol(@invoice_equivalent.amount) %></td>
      </tr>
      <tr>
        <td colspan="1"  class="subtotal-title">Retención en la fuente</td>
        <td colspan="1"  class="subtotal-value"><%= humanized_money_with_symbol(@invoice_equivalent.retention) %></td>
      </tr>
      <tr>
        <td colspan="1"  class="subtotal-title" >Total a pagar</td>
        <td colspan="1"  class="subtotal-value"><%= humanized_money_with_symbol(@invoice_equivalent.total) %></td>
      </tr>
    </table>
  </div>
  <br>
  <div class="pdf-bottom">
    <span class="text-center made-by">ELABORADO POR</span>
    <span class="text-center accepeted-by">ACEPTADA, FIRMA Y/O SELLO Y FECHA</span>
  </div>


</div>

app/views/invoice_equivalents/show.html.erb
<%= render 'shared/sidebar' %>
<div class="page-content-wrapper">
  <h3 class="expense-title text-center">Documento equivalente num: <%= @invoice_equivalent.formated_number %></h4>
  <h4 class="business-title text-center">Por concepto de: <%= @invoice_equivalent.description.downcase %></h4>
  <div class="table-container-simple flex flex-center">
    <div class="show-actions">
      <%= link_to print_business_invoice_equivalent_path(@business, @invoice_equivalent),class: "btn show-action-btn", target: :blank  do %>
        Imprimir
        <i class="material-icons"> print </i>
      <% end %>
      <%= link_to edit_business_invoice_equivalent_path(@business, @invoice_equivalent), class: "btn show-action-btn" do %>
        Editar
        <i class="material-icons"> create </i>
      <% end %>
      <%= link_to business_invoice_equivalent_path(@business, @invoice_equivalent), class: "btn show-action-btn", method: :delete, data: { confirm: '¿Estás seguro?' } do %>
        Eliminar
        <i class="material-icons"> delete </i>
      <% end %>
    </div>
    <div class="table-container show-table">
      <div class="table">
        <div class="table-row">
          <div class="table-header">Número</div>
          <div class="table-data"><%= @invoice_equivalent.formated_number %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Beneficiario</div>
          <div class="table-data"><%= @invoice_equivalent.contact.name %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Detalle</div>
          <div class="table-data"><%= @invoice_equivalent.description %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Fecha Operación</div>
          <div class="table-data"><%= @invoice_equivalent.date %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Valor de la operación</div>
          <div class="table-data"><%= humanized_money_with_symbol @invoice_equivalent.amount %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Retención en la fuente</div>
          <div class="table-data"><%= humanized_money_with_symbol @invoice_equivalent.retention %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Total a pagar</div>
          <div class="table-data"><%= humanized_money_with_symbol @invoice_equivalent.total %></div>
        </div>
        <div class="table-row">
          <div class="table-header">
            Adjuntos:
          </div>
          <div class="table-data">
            <% @attachments.each do |attachment| %>
            <div class="attachments-container">
              <% attachments_delete_params = {
                  invoice_equivalent: {
                    business_id: @business.id,
                    attachments_attributes: {
                      id: attachment.id,
                      _destroy: true
                    }
                  },
                }
              %>
              <% if attachment.file.file.storage_type == "private" %>
                <%= link_to attachment.name, cl_private_download_url(attachment.file.file.public_id, attachment.file.format), target: :blank  %>
              <% else %>
                <%= link_to attachment.name, cl_image_path(attachment.file.filename), target: :blank  %>
              <% end %>
              <%= link_to business_invoice_equivalent_path(@invoice_equivalent, attachments_delete_params), class: "delete-attachement", method: :patch, data: { confirm: 'Are you sure?' } do%>
                <i class="material-icons"> delete </i>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="table-row">
          <div class="table-header">Observaciones</div>
          <div class="table-data white-space-wrap"><%= @invoice_equivalent.observation %></div>
        </div>
      </div>
    </div>
  </div>
</div>