config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'businesses#index', as: :authenticated_root
  end
  unauthenticated :user do
    root to: 'pages#home'
  end
  devise_for :users,
  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :businesses do
    resources :items, only: :index, to: "businesses#items"
    resources :contacts do
      member do
        get '/invoices', to: "contacts#invoices", defaults: { format: 'pdf' }
      end
    end

    resources :expenses do
      member do
        get '/print', to: "expenses#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :expenses do
      member do
        get '/print', to: "expenses#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :invoices do
      member do
        get '/print', to: "invoices#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :payments do
      member do
        get '/print', to: "payments#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :invoice_equivalents do
      member do
        get '/print', to: "invoice_equivalents#print", defaults: { format: 'pdf' }
        post :toggle_printed
      end
    end

    resources :attachments, only: :show
    resources :exports, only: [:new, :create]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  before_validation :add_payment_number, on: :create
  validate :amount_is_less_than_debt

  belongs_to :business
  belongs_to :contact
  belongs_to :invoice, optional: true

  enum payment_method: ["Efectivo",
                        "Consignación",
                        "Transferencia",
                        "Cheque",
                        "Tarjeta crédito",
                        "Tarjeta débito",
                        "Otro",
                        "Tarjeta E-Prepago"]

  enum retention_type: ["Arrendamiento de bienes muebles - (4%)",
                        "Arrendamiento de bienes raíces - (3.5%)",
                        "Compras - (2.5%)",
                        "Compras - (3.5%)",
                        "Honorarios y comisiones - (10%)",
                        "Honorarios y comisiones - (11%)",
                        "Servicios de aseo y vigilancia - (2%)",
                        "Servicios de hoteles y restaurantes - (3.5%)",
                        "Servicios en general - (4%)",
                        "Servicios en general - (6%)",
                        "ReteICA - (0%)",
                        "ReteIVA - (15%)",
                        "Transporte de carga - (1%)",
                        "Servicios tecnológicos - (3.5%)"]

  monetize :amount_cents
  monetize :retention_cents

  def formated_number
    format("%03d", number)
  end

  def pdf_file_name
    "#{formated_number} RC #{description}"
  end

  def formated_date
    date.strftime("%d/%m/%Y")
  end

  def total
    amount + retention
  end

  def retention_full_name
    return unless retention

    if retention_type && retention
      "#{ActionController::Base.helpers.humanized_money_with_symbol retention} - #{retention_type}"
    elsif retention
      "#{ActionController::Base.helpers.humanized_money_with_symbol retention}"
    end
  end

  private

  def add_payment_number
    self.number = business.payments.size + 1
  end

  def amount_is_less_than_debt
    return unless invoice

    debt_amount = invoice.debt + ((amount_cents_was + retention_cents_was) / 100).to_money
    errors.add(:amount, "la suma de retención y valor recibido supera la deuda ") if total > debt_amount
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_business, except: :update
  before_action :set_payment, only: %i[show edit update destroy print toggle_printed]

  def index
    @payments = policy_scope(Payment.where(business: @business).order(number: :desc).includes(:contact).paginate(page: params[:page]))
  end

  def show
    authorize @payment
  end

  def new
    @payment = Payment.new
    authorize @business, :business_of_current_user?
  end

  def create
    @payment = Payment.new(payment_params)
    authorize @business, :business_of_current_user?
    if @payment.save
      flash[:notice] = "Pago registrado existosamente"
      redirect_to business_payment_path @business, @payment
    else
      render :new
    end
  end

  def edit
    authorize @payment
    @invoice = @payment.invoice
  end

  def update
    @business = Business.find(payment_params[:business_id])
    authorize @business, :business_of_current_user?
    if @payment.update(payment_params)
      flash[:notice] = "Pago actualizado existosamente"
      redirect_to business_payment_path @business, @payment
    else
      render 'edit'
    end
  end

  def destroy
    authorize @payment
    @payment.destroy
    flash[:notice] = "Pago eliminado existosamente"
    redirect_to business_payments_path(@business)
  end

  def print
    authorize @payment
    @contact = @payment.contact
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: @payment.pdf_file_name, layout: 'pdf.html', show_as_html: params.key?('debug')   # Excluding ".pdf" extension.
      end
    end
  end

  def toggle_printed
    @payment.update(printed: !@payment.printed)
  end

  private

  def set_payment
    @payment = Payment.includes(:contact).find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(
      :number,
      :contact_id,
      :invoice_id,
      :payment_method,
      :date,
      :description,
      :amount,
      :retention,
      :retention_type,
      :business_id,
      :observation
    )
  end
end

app/views/payments/edit.html.erb
<%= render "shared/sidebar" %>
<div class="page-content-wrapper">
  <div class="form-container">
    <div class="new-property-form-container new-owner-form-container">
      <div class="new-property-form-heading">
        <h1>Edita el recibo de caja número <%= @payment.formated_number %></h1>
      </div>
      <%= render 'shared/payment-form' %>
    </div>
  </div>
</div>

app/views/payments/index.html.erb
<%= render 'shared/sidebar' %>
<div class="page-content-wrapper">
  <% if @payments.size == 0 %>
    <h3 class="alert alert-blue property-title text-center">
      <i class="material-icons">
       info
      </i>
      Aún no tienes ningún pago recibido registrado, agrega uno para comenzar
    </h3>
  <% else %>
    <h1 class="app-index-title">Lista de Pagos Recibidos</h1>
    <div class="table-container table-container--no-margin-bottom">
      <div class="table">
        <div class="table-row">
          <div class="table-header">Número</div>
          <div class="table-header">Clientes</div>
          <div class="table-header">Detalle</div>
          <div class="table-header">Fecha</div>
          <div class="table-header">Forma de Pago</div>
          <div class="table-header">Monto</div>
          <div class="table-header">Acciones</div>
          <div class="table-header">Impreso</div>
        </div>
        <% @payments.each do |payment| %>
            <div class="table-row-link table-row"
                 data-controller="table-row"
                 data-table-row-location="<%= business_payment_path(@business, payment)%>"
            >
              <div class="table-data" data-action="click->table-row#visitLocation"><%= payment.formated_number %></div>
              <div class="table-data" data-action="click->table-row#visitLocation"><%= payment.contact.name %></div>
              <div class="table-data" data-action="click->table-row#visitLocation"><%= payment.description %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= payment.date %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= payment.payment_method %></div>
              <div class="table-data white-space-no-wrap" data-action="click->table-row#visitLocation"><%= humanized_money_with_symbol payment.amount %></div>
              <div class="table-data white-space-no-wrap">
                <%= link_to print_business_payment_path(@business, payment), target: :blank  do %>
                  <i class="material-icons"> print </i>
                <% end %>
                <%= link_to edit_business_payment_path(@business, payment), class: "edit-property" do %>
                  <i class="material-icons"> create </i>
                <% end %>
                <%= link_to business_payment_path(@business, payment), class: "destroy-property", method: :delete, data: { confirm: '¿Estás seguro?' } do %>
                  <i class="material-icons"> delete </i>
                <% end %>
              </div>
              <div class="table-data">
                <%= check_box_tag 'printed', payment.id, payment.printed,
                    data: {
                      remote: true,
                      url: toggle_printed_business_payment_path(@business, payment),
                      method: :post
                    }
                %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
    <%= will_paginate @payments, renderer: BootstrapPagination::Rails, class: "hidden-sm hidden-xs" %>
    <%= will_paginate @payments, renderer: BootstrapPagination::Rails, page_links: false, class: "hidden-lg hidden-md" %>
  <% end %>
  <a class="mdc-fab fab-bottom-right fab-color" aria-label="Favorite" href="<%= new_business_payment_path %>">
    <i class="material-icons">
      attach_money
    </i>
   +
  </a>
</div>

app/views/payments/new.html.erb
<%= render "shared/sidebar" %>
<div class="page-content-wrapper">
  <div class="form-container">
    <div class="new-property-form-container new-expense-form-container">
      <div class="new-property-form-heading">
        <h1>Agregar un nuevo pago recibido a <%= @business.name %></h1>
      </div>
      <%= render 'shared/payment-form' %>
    </div>
  </div>
</div>

app/views/payments/print.pdf.erb
<%= content_for :title, @payment.pdf_file_name %>

<div class="pdf-container">
  <div class="pdf-top">
    <% if @business.logo.present? %>
      <div class="bussines-logo" style="background-image: url('<%= cl_image_path @business.logo, width: 300, height: 100, crop: :fill; %>')">
      </div>
    <% end %>
    <div class="bussines-info">
      <h3 class="text-center"><%= @business.name %></h3>
      <p class="text-center" >NIT <%= @business.tax_id %></p>
      <p class="text-center" ><%= @business.address %></p>
      <p class="text-center" ><%= @business.cell_phone %></p>
      <p class="text-center" ><%= @business.email %></p>
    </div>
    <div class="expense-number-box">
      <h4 class="text-center">Recibo de caja</h4>
      <h3 class="text-center">No. <%= @payment.formated_number %></h3>
    </div>
  </div>
  <div class="pdf-center">
    <table class="benificary-info">
      <tr>
        <th colspan="1">Recibimos de</th>
        <td colspan="3"><%= @contact.name %></td>
        <th colspan="1" rowspan="1" class="expense-date-header">Fecha (DD/MM/AA)</td>
      </tr>
      <tr>
        <th colspan="1">Dirección</th>
        <td colspan="3"><%= @contact.address %></td>
        <td rowspan="4" class="expense-date-value"><h3><%= @payment.formated_date %></h3></td>
      </tr>
      <tr>
        <th colspan="1">Ciudad</th>
        <td colspan="3"><%= @contact.city %></td>
      </tr>
      <tr>
        <th colspan="1"><%= @contact.phone_numbers_label_for_pdf %></th>
        <td colspan="1"><%= @contact.phone_numbers %></td>
        <th colspan="1">Método de Pago</th>
        <td colspan="1"><%= @payment.payment_method %></td>
      </tr>
      <tr>
        <th colspan="1"><%= @contact.tax_id_type.split("-")[0] %></th>
        <td colspan="1"><%= @contact.tax_id %></td>
        <th colspan="1">Cuenta</th>
        <td colspan="1"></td>
      </tr>
    </table>
    <table class="expense-info">
      <thead>
        <tr>
          <th colspan="4">Concepto</th>
          <th colspan="1">Valor</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="4"><%= @payment.description %></td>
          <td colspan="1" class="concept-value"><%= humanized_money_with_symbol(@payment.amount) %></td>
        </tr>
        <% 9.times do %>
          <tr>
            <td colspan="4"> </td>
            <td colspan="1" class="concept-value"> </td>
          </tr>
        <% end %>
        <tr>
          <td colspan="4" class="retention-box">Retenciones: <%= @payment.retention_full_name %></td>
          <td></td>
        </tr>
        <tr class="force-border-bottom">
          <td colspan="3" rowspan="2" class="observations-box">Observaciones: <%= @payment.observation %></td>
          <td colspan="1" rowspan="2" class="total-text">Total</td>
          <td colspan="1" rowspan="2" class="total-value"><%= humanized_money_with_symbol(@payment.amount) %></td>
        </tr>
        <tr>
          <!-- Dejar esta fila en blanco para el rowspan -->
        </tr>
      </tbody>
    </table>
  </div>
  <br>
  <div class="pdf-bottom">
    <span class="text-center made-by">ELABORADO POR</span>
    <span class="text-center accepeted-by">ACEPTADA, FIRMA Y/O SELLO Y FECHA</span>
  </div>


</div>

app/views/payments/show.html.erb
<%= render 'shared/sidebar' %>
<div class="page-content-wrapper">
  <h3 class="expense-title text-center">Recibo de caja num: <%= @payment.formated_number %></h4>
  <h4 class="business-title text-center">Por concepto de: <%= @payment.description.downcase %></h4>
  <div class="table-container-simple flex flex-center">
    <div class="show-actions">
      <%= link_to print_business_payment_path(@business, @payment),class: "btn show-action-btn", target: :blank  do %>
        Imprimir
        <i class="material-icons"> print </i>
      <% end %>
      <%= link_to edit_business_payment_path(@business, @payment), class: "btn show-action-btn" do %>
        Editar
        <i class="material-icons"> create </i>
      <% end %>
      <%= link_to business_payment_path(@business, @payment), class: "btn show-action-btn", method: :delete, data: { confirm: '¿Estás seguro?' } do %>
        Eliminar
        <i class="material-icons"> delete </i>
      <% end %>
    </div>
    <div class="table-container show-table">
      <div class="table">
        <div class="table-row">
          <div class="table-header">Número</div>
          <div class="table-data"><%= @payment.formated_number %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Beneficiario</div>
          <div class="table-data"><%= @payment.contact.name %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Detalle</div>
          <div class="table-data"><%= @payment.description %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Fecha</div>
          <div class="table-data"><%= @payment.date %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Forma de Pago</div>
          <div class="table-data"><%= @payment.payment_method %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Monto</div>
          <div class="table-data"><%= humanized_money_with_symbol @payment.amount %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Retención</div>
          <div class="table-data"><%= @payment.retention_full_name %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Observaciones</div>
          <div class="table-data white-space-wrap"><%= @payment.observation %></div>
        </div>
      </div>
    </div>
  </div>
</div>